version: '2'
services:
  lanzadorServicios:
    image: ignacioibanez/lanzadorstacks:latest
    environment:
      URL_ENTRADAS: ${URL_ENTRADAS}
    stdin_open: true
    entrypoint:
        - sh
        - -c
        - python lanzadorServicios.py $$URL_ENTRADAS 
    tty: true
